/* 

	MIT license.

	Copyright 2017 Aaron Flin

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to
	deal in the Software without restriction, including without limitation the
	rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
	sell copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
	IN THE SOFTWARE.

*/

#ifndef _DOUBLE_TO_STR_H_

#define _DOUBLE_TO_STR_H_


/******************** double to string functions and definitions ***********/

/* takes a double and generates a string representation that can
   be sorted (ascii) and will also be in numerical order
   
   **str is pointer to a char array which must be pre-allocated and 
         at least 15 chars
*/
void doubletostr32(double x, char **str, int safe);

/* convert a string generated by doubletostr32 back to a double */
double str32todouble (char *s);


#endif
